In [4]:
import pandas as pd

In [5]:
df = pd.read_parquet('../../fsx1/emory-mimic-icu/tables/microbiologyevents.parquet')

In [6]:
# Display the DataFrame
df=df.drop(["microevent_id"],axis=1)
df.head(5)

,subject_id,hadm_id,micro_specimen_id,order_provider_id,chartdate,charttime,spec_itemid,spec_type_desc,test_seq,storedate,...,org_name,isolate_num,quantity,ab_itemid,ab_name,dilution_text,dilution_comparison,dilution_value,interpretation,comments
0,17845954,7804291290,247186183,None,2000-12-20,2000-12-20 00:15:00,NaN,CULTURE SPEC,NaN,NaT,...,ESCHERICHIA COLI,NaN,None,309629,Ticarcillin/Clavulanate $$$,None,None,NaN,SENSITIVE,None
1,91202312,4585460973,150275897,None,2010-01-20,2010-01-20 14:24:00,NaN,Not Recorded,NaN,NaT,...,ESCHERICHIA COLI,NaN,None,309663,Gentamicin $,None,None,NaN,SENSITIVE,None
2,69560727,56956259168,1763718829,None,2009-11-20,2009-11-20 15:00:00,NaN,Not Recorded,NaN,NaT,...,STAPHYLOCOCCUS AUREUS,NaN,None,309631,Tetracycline $,None,None,NaN,SENSITIVE,None
3,80355279,3148230161,5052259433,None,2009-07-14,2009-07-14 12:24:00,NaN,Not Recorded,NaN,NaT,...,ENTEROBACTER CLOACAE,NaN,None,309677,Cefuroxime $$,None,None,NaN,RESISTANT,None
4,77548363,83710681136,6856415505,None,2009-09-16,2009-09-16 08:43:00,NaN,Not Recorded,NaN,NaT,...,ESCHERICHIA COLI,NaN,None,309692,Cefepime $$,None,None,NaN,SENSITIVE,None

In [7]:
df["order_provider_id"].unique()

array([None], dtype=object)

In [8]:
df["spec_itemid"].unique()

array([nan])

In [9]:
df["storedate"].unique()

<DatetimeArray>
['NaT']
Length: 1, dtype: datetime64[us]

In [10]:
df["isolate_num"].unique()

array([nan])

In [11]:
df["quantity"].unique()

array([None], dtype=object)

In [12]:
df["dilution_comparison"].unique()

array([None], dtype=object)

In [13]:
df["comments"].unique()

array([None], dtype=object)

In [14]:
df=df.drop(["order_provider_id", "spec_itemid", "storedate", "isolate_num", "quantity", "dilution_comparison", "comments"], axis=1)
df

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,test_seq,storetime,test_itemid,test_name,org_itemid,org_name,ab_itemid,ab_name,dilution_text,dilution_value,interpretation
0,17845954,7804291290,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,NaN,2000-12-22 09:28:00,NaN,URINE CULTURE & COLONY COUNT,NaN,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,None,NaN,SENSITIVE
1,91202312,4585460973,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,NaN,2010-01-22 10:39:00,NaN,URINE CULTURE & COLONY COUNT,NaN,ESCHERICHIA COLI,309663,Gentamicin $,None,NaN,SENSITIVE
2,69560727,56956259168,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,NaN,2009-11-22 14:22:00,NaN,BLOOD CULTURE BACTERIA/YEAST,NaN,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,None,NaN,SENSITIVE
3,80355279,3148230161,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,NaN,2009-07-16 09:41:00,NaN,RESPIRATORY CULTURE,NaN,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,None,NaN,RESISTANT
4,77548363,83710681136,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,NaN,2009-09-18 08:55:00,NaN,URINE CULTURE & COLONY COUNT,NaN,ESCHERICHIA COLI,309692,Cefepime $$,None,NaN,SENSITIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2652494,85721694,47555266007,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,NaN,2022-01-10 18:39:43,NaN,Not Recorded,NaN,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,None,NaN,Susceptible
2652495,85721694,47555266007,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,NaN,2022-01-13 08:37:54,NaN,URINE CULTURE & COLONY COUNT,NaN,Enterococcus faecium,309703,Ampicillin $,None,NaN,Resistant
2652496,63932307,52318894882,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,NaN,2022-08-10 07:43:41,NaN,URINE CULTURE & COLONY COUNT,NaN,Pseudomonas aeruginosa,309663,Gentamicin $,None,NaN,Susceptible
2652497,22725484,9645436148,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,NaN,2022-11-23 17:40:08,NaN,URINE CULTURE & COLONY COUNT,NaN,Klebsiella oxytoca,309692,Cefepime $$,None,NaN,Susceptible
2652498,55563410,45291696088,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,NaN,2022-04-14 17:53:53,NaN,URINE CULTURE & COLONY COUNT,NaN,Escherichia coli,309641,Piperacillin/Tazobactam $$,None,NaN,Susceptible

In [15]:
df.describe()

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,test_seq,storetime,test_itemid,org_itemid,ab_itemid,dilution_value
count,2.652499e+06,2.652499e+06,2.652499e+06,2652499,2652499,0.0,2652499,0.0,0.0,2.652499e+06,0.0
mean,5.507908e+07,4.356886e+10,4.329347e+13,2016-09-14 21:04:54.798376,2016-09-15 10:38:43.114016,NaN,2016-09-19 08:09:50.088266,NaN,NaN,6.101215e+07,NaN
min,1.000010e+07,1.037535e+07,1.465364e+08,1921-02-05 00:00:00,1921-02-05 08:41:00,NaN,2000-12-22 09:28:00,NaN,NaN,3.096250e+05,NaN
25%,3.256393e+07,1.245997e+10,1.414985e+13,2014-03-25 00:00:00,2014-03-25 19:40:00,NaN,2014-03-29 13:28:58,NaN,NaN,3.096410e+05,NaN
50%,5.521009e+07,4.169118e+10,4.301894e+13,2016-11-18 00:00:00,2016-11-18 14:00:00,NaN,2016-11-22 13:17:17,NaN,NaN,3.096710e+05,NaN
75%,7.750626e+07,7.072880e+10,7.142050e+13,2019-07-25 00:00:00,2019-07-25 19:23:00,NaN,2019-07-30 06:22:04,NaN,NaN,3.096990e+05,NaN
max,9.999942e+07,5.192079e+11,9.999982e+13,2022-11-20 00:00:00,2022-11-20 16:42:00,NaN,2022-11-23 17:40:08,NaN,NaN,4.035437e+09,NaN
std,2.594445e+07,3.112045e+10,3.223025e+13,NaN,NaN,NaN,NaN,NaN,NaN,2.463829e+08,NaN

In [16]:
df=df.drop(["test_seq", "test_itemid", "org_itemid", "dilution_value"], axis=1)
df

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,dilution_text,interpretation
0,17845954,7804291290,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,2000-12-22 09:28:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,None,SENSITIVE
1,91202312,4585460973,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,2010-01-22 10:39:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309663,Gentamicin $,None,SENSITIVE
2,69560727,56956259168,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,2009-11-22 14:22:00,BLOOD CULTURE BACTERIA/YEAST,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,None,SENSITIVE
3,80355279,3148230161,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,2009-07-16 09:41:00,RESPIRATORY CULTURE,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,None,RESISTANT
4,77548363,83710681136,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,2009-09-18 08:55:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309692,Cefepime $$,None,SENSITIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2652494,85721694,47555266007,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,2022-01-10 18:39:43,Not Recorded,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,None,Susceptible
2652495,85721694,47555266007,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,2022-01-13 08:37:54,URINE CULTURE & COLONY COUNT,Enterococcus faecium,309703,Ampicillin $,None,Resistant
2652496,63932307,52318894882,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,2022-08-10 07:43:41,URINE CULTURE & COLONY COUNT,Pseudomonas aeruginosa,309663,Gentamicin $,None,Susceptible
2652497,22725484,9645436148,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,2022-11-23 17:40:08,URINE CULTURE & COLONY COUNT,Klebsiella oxytoca,309692,Cefepime $$,None,Susceptible
2652498,55563410,45291696088,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,2022-04-14 17:53:53,URINE CULTURE & COLONY COUNT,Escherichia coli,309641,Piperacillin/Tazobactam $$,None,Susceptible

In [17]:
df["dilution_text"].unique()

array([None], dtype=object)

In [18]:
df=df.drop(["dilution_text"],axis=1)
df

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,interpretation
0,17845954,7804291290,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,2000-12-22 09:28:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,SENSITIVE
1,91202312,4585460973,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,2010-01-22 10:39:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309663,Gentamicin $,SENSITIVE
2,69560727,56956259168,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,2009-11-22 14:22:00,BLOOD CULTURE BACTERIA/YEAST,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,SENSITIVE
3,80355279,3148230161,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,2009-07-16 09:41:00,RESPIRATORY CULTURE,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,RESISTANT
4,77548363,83710681136,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,2009-09-18 08:55:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309692,Cefepime $$,SENSITIVE
...,...,...,...,...,...,...,...,...,...,...,...,...
2652494,85721694,47555266007,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,2022-01-10 18:39:43,Not Recorded,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,Susceptible
2652495,85721694,47555266007,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,2022-01-13 08:37:54,URINE CULTURE & COLONY COUNT,Enterococcus faecium,309703,Ampicillin $,Resistant
2652496,63932307,52318894882,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,2022-08-10 07:43:41,URINE CULTURE & COLONY COUNT,Pseudomonas aeruginosa,309663,Gentamicin $,Susceptible
2652497,22725484,9645436148,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,2022-11-23 17:40:08,URINE CULTURE & COLONY COUNT,Klebsiella oxytoca,309692,Cefepime $$,Susceptible
2652498,55563410,45291696088,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,2022-04-14 17:53:53,URINE CULTURE & COLONY COUNT,Escherichia coli,309641,Piperacillin/Tazobactam $$,Susceptible

In [19]:
df["subject_id_hadm_id"]=df["subject_id"].astype(str)+'_'+df['hadm_id'].astype(str)

In [20]:
df

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,interpretation,subject_id_hadm_id
0,17845954,7804291290,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,2000-12-22 09:28:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,SENSITIVE,17845954_7804291290
1,91202312,4585460973,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,2010-01-22 10:39:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309663,Gentamicin $,SENSITIVE,91202312_4585460973
2,69560727,56956259168,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,2009-11-22 14:22:00,BLOOD CULTURE BACTERIA/YEAST,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,SENSITIVE,69560727_56956259168
3,80355279,3148230161,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,2009-07-16 09:41:00,RESPIRATORY CULTURE,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,RESISTANT,80355279_3148230161
4,77548363,83710681136,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,2009-09-18 08:55:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309692,Cefepime $$,SENSITIVE,77548363_83710681136
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2652494,85721694,47555266007,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,2022-01-10 18:39:43,Not Recorded,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,Susceptible,85721694_47555266007
2652495,85721694,47555266007,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,2022-01-13 08:37:54,URINE CULTURE & COLONY COUNT,Enterococcus faecium,309703,Ampicillin $,Resistant,85721694_47555266007
2652496,63932307,52318894882,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,2022-08-10 07:43:41,URINE CULTURE & COLONY COUNT,Pseudomonas aeruginosa,309663,Gentamicin $,Susceptible,63932307_52318894882
2652497,22725484,9645436148,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,2022-11-23 17:40:08,URINE CULTURE & COLONY COUNT,Klebsiella oxytoca,309692,Cefepime $$,Susceptible,22725484_9645436148
2652498,55563410,45291696088,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,2022-04-14 17:53:53,URINE CULTURE & COLONY COUNT,Escherichia coli,309641,Piperacillin/Tazobactam $$,Susceptible,55563410_45291696088

In [21]:
df=df.drop_duplicates()

In [22]:
df

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,interpretation,subject_id_hadm_id
0,17845954,7804291290,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,2000-12-22 09:28:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,SENSITIVE,17845954_7804291290
1,91202312,4585460973,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,2010-01-22 10:39:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309663,Gentamicin $,SENSITIVE,91202312_4585460973
2,69560727,56956259168,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,2009-11-22 14:22:00,BLOOD CULTURE BACTERIA/YEAST,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,SENSITIVE,69560727_56956259168
3,80355279,3148230161,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,2009-07-16 09:41:00,RESPIRATORY CULTURE,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,RESISTANT,80355279_3148230161
4,77548363,83710681136,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,2009-09-18 08:55:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309692,Cefepime $$,SENSITIVE,77548363_83710681136
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2652494,85721694,47555266007,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,2022-01-10 18:39:43,Not Recorded,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,Susceptible,85721694_47555266007
2652495,85721694,47555266007,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,2022-01-13 08:37:54,URINE CULTURE & COLONY COUNT,Enterococcus faecium,309703,Ampicillin $,Resistant,85721694_47555266007
2652496,63932307,52318894882,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,2022-08-10 07:43:41,URINE CULTURE & COLONY COUNT,Pseudomonas aeruginosa,309663,Gentamicin $,Susceptible,63932307_52318894882
2652497,22725484,9645436148,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,2022-11-23 17:40:08,URINE CULTURE & COLONY COUNT,Klebsiella oxytoca,309692,Cefepime $$,Susceptible,22725484_9645436148
2652498,55563410,45291696088,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,2022-04-14 17:53:53,URINE CULTURE & COLONY COUNT,Escherichia coli,309641,Piperacillin/Tazobactam $$,Susceptible,55563410_45291696088

In [23]:
#Remove rows with missing values
df=df.dropna(how='all')
df

,subject_id,hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,interpretation,subject_id_hadm_id
0,17845954,7804291290,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,2000-12-22 09:28:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,SENSITIVE,17845954_7804291290
1,91202312,4585460973,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,2010-01-22 10:39:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309663,Gentamicin $,SENSITIVE,91202312_4585460973
2,69560727,56956259168,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,2009-11-22 14:22:00,BLOOD CULTURE BACTERIA/YEAST,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,SENSITIVE,69560727_56956259168
3,80355279,3148230161,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,2009-07-16 09:41:00,RESPIRATORY CULTURE,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,RESISTANT,80355279_3148230161
4,77548363,83710681136,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,2009-09-18 08:55:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309692,Cefepime $$,SENSITIVE,77548363_83710681136
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2652494,85721694,47555266007,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,2022-01-10 18:39:43,Not Recorded,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,Susceptible,85721694_47555266007
2652495,85721694,47555266007,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,2022-01-13 08:37:54,URINE CULTURE & COLONY COUNT,Enterococcus faecium,309703,Ampicillin $,Resistant,85721694_47555266007
2652496,63932307,52318894882,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,2022-08-10 07:43:41,URINE CULTURE & COLONY COUNT,Pseudomonas aeruginosa,309663,Gentamicin $,Susceptible,63932307_52318894882
2652497,22725484,9645436148,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,2022-11-23 17:40:08,URINE CULTURE & COLONY COUNT,Klebsiella oxytoca,309692,Cefepime $$,Susceptible,22725484_9645436148
2652498,55563410,45291696088,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,2022-04-14 17:53:53,URINE CULTURE & COLONY COUNT,Escherichia coli,309641,Piperacillin/Tazobactam $$,Susceptible,55563410_45291696088

In [31]:
df=df.drop(["subject_id", "hadm_id"], axis=1)
df

,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,interpretation,subject_id_hadm_id
0,247186183,2000-12-20,2000-12-20 00:15:00,CULTURE SPEC,2000-12-22 09:28:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309629,Ticarcillin/Clavulanate $$$,SENSITIVE,17845954_7804291290
1,150275897,2010-01-20,2010-01-20 14:24:00,Not Recorded,2010-01-22 10:39:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309663,Gentamicin $,SENSITIVE,91202312_4585460973
2,1763718829,2009-11-20,2009-11-20 15:00:00,Not Recorded,2009-11-22 14:22:00,BLOOD CULTURE BACTERIA/YEAST,STAPHYLOCOCCUS AUREUS,309631,Tetracycline $,SENSITIVE,69560727_56956259168
3,5052259433,2009-07-14,2009-07-14 12:24:00,Not Recorded,2009-07-16 09:41:00,RESPIRATORY CULTURE,ENTEROBACTER CLOACAE,309677,Cefuroxime $$,RESISTANT,80355279_3148230161
4,6856415505,2009-09-16,2009-09-16 08:43:00,Not Recorded,2009-09-18 08:55:00,URINE CULTURE & COLONY COUNT,ESCHERICHIA COLI,309692,Cefepime $$,SENSITIVE,77548363_83710681136
...,...,...,...,...,...,...,...,...,...,...,...
2652494,43772212292658,2022-01-06,2022-01-06 08:20:00,Mini Bronchoalveolar Lavage,2022-01-10 18:39:43,Not Recorded,Pseudomonas aeruginosa,1241653369,Ceftolozane/Tazobactam $$$,Susceptible,85721694_47555266007
2652495,93594322317404,2022-01-11,2022-01-11 11:02:00,Urine,2022-01-13 08:37:54,URINE CULTURE & COLONY COUNT,Enterococcus faecium,309703,Ampicillin $,Resistant,85721694_47555266007
2652496,42801597281046,2022-08-06,2022-08-06 15:14:00,Urine,2022-08-10 07:43:41,URINE CULTURE & COLONY COUNT,Pseudomonas aeruginosa,309663,Gentamicin $,Susceptible,63932307_52318894882
2652497,52709187002906,2022-11-20,2022-11-20 16:42:00,Urine,2022-11-23 17:40:08,URINE CULTURE & COLONY COUNT,Klebsiella oxytoca,309692,Cefepime $$,Susceptible,22725484_9645436148
2652498,59158391516126,2022-04-10,2022-04-10 18:45:00,Urine,2022-04-14 17:53:53,URINE CULTURE & COLONY COUNT,Escherichia coli,309641,Piperacillin/Tazobactam $$,Susceptible,55563410_45291696088

## 2633445 rows

## moving to icustays tables

In [24]:
df_icustays=pd.read_parquet("../../fsx1/emory-mimic-icu/tables/icustays.parquet")

In [25]:
df_icustays

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10000683,29770490036,1,5E ICU EUH,5E ICU EUH,2015-05-12 18:29:30,2015-05-13 16:51:55,0.932234
1,10000683,29770490036,2,5E ICU EUH,5E ICU EUH,2015-05-13 17:16:17,2015-05-13 22:14:51,0.207338
2,10000683,87659254514,3,5E ICU EUH,5E ICU EUH,2015-09-08 12:10:12,2015-09-09 14:28:37,1.096123
3,10000788,54733468003,4,2SW ICU SJH,2SW ICU SJH,2017-02-01 14:17:11,2017-02-12 10:27:44,10.840660
4,10001527,90885934252,5,5E ICU EUH,5E ICU EUH,2012-09-27 21:45:17,2012-09-28 15:00:27,0.718866
...,...,...,...,...,...,...,...,...
189220,99995283,41747642827,189221,41 CCU ECLH,41 CCU ECLH,2015-05-17 07:53:44,2015-05-18 15:39:21,1.323345
189221,99995283,76374197374,189222,41 CCU ECLH,41 CCU ECLH,2018-04-08 20:56:03,2018-04-09 17:58:46,0.876887
189222,99995283,98208879646,189223,PACU II ECLH,21 ICU ECLH,2010-12-28 06:16:21,2010-12-29 12:13:20,1.247905
189223,99997196,59639511443,189224,2SW ICU SJH,2SW ICU SJH,2017-09-23 12:38:48,2017-09-24 15:21:54,1.113264
189224,99997229,71249926344,189225,3G CCU EUH,3G CCU EUH,2021-03-20 01:33:40,2021-03-22 21:10:46,2.817430

In [26]:
df_icustays= df_icustays.drop_duplicates()

In [27]:
#Remove rows with missing values
df_icustays=df_icustays.dropna(how='all')
df_icustays

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10000683,29770490036,1,5E ICU EUH,5E ICU EUH,2015-05-12 18:29:30,2015-05-13 16:51:55,0.932234
1,10000683,29770490036,2,5E ICU EUH,5E ICU EUH,2015-05-13 17:16:17,2015-05-13 22:14:51,0.207338
2,10000683,87659254514,3,5E ICU EUH,5E ICU EUH,2015-09-08 12:10:12,2015-09-09 14:28:37,1.096123
3,10000788,54733468003,4,2SW ICU SJH,2SW ICU SJH,2017-02-01 14:17:11,2017-02-12 10:27:44,10.840660
4,10001527,90885934252,5,5E ICU EUH,5E ICU EUH,2012-09-27 21:45:17,2012-09-28 15:00:27,0.718866
...,...,...,...,...,...,...,...,...
189220,99995283,41747642827,189221,41 CCU ECLH,41 CCU ECLH,2015-05-17 07:53:44,2015-05-18 15:39:21,1.323345
189221,99995283,76374197374,189222,41 CCU ECLH,41 CCU ECLH,2018-04-08 20:56:03,2018-04-09 17:58:46,0.876887
189222,99995283,98208879646,189223,PACU II ECLH,21 ICU ECLH,2010-12-28 06:16:21,2010-12-29 12:13:20,1.247905
189223,99997196,59639511443,189224,2SW ICU SJH,2SW ICU SJH,2017-09-23 12:38:48,2017-09-24 15:21:54,1.113264
189224,99997229,71249926344,189225,3G CCU EUH,3G CCU EUH,2021-03-20 01:33:40,2021-03-22 21:10:46,2.817430

In [28]:
df_icustays["subject_id_hadm_id"]=df_icustays["subject_id"].astype(str)+'_'+df_icustays['hadm_id'].astype(str)
df_icustays

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los,subject_id_hadm_id
0,10000683,29770490036,1,5E ICU EUH,5E ICU EUH,2015-05-12 18:29:30,2015-05-13 16:51:55,0.932234,10000683_29770490036
1,10000683,29770490036,2,5E ICU EUH,5E ICU EUH,2015-05-13 17:16:17,2015-05-13 22:14:51,0.207338,10000683_29770490036
2,10000683,87659254514,3,5E ICU EUH,5E ICU EUH,2015-09-08 12:10:12,2015-09-09 14:28:37,1.096123,10000683_87659254514
3,10000788,54733468003,4,2SW ICU SJH,2SW ICU SJH,2017-02-01 14:17:11,2017-02-12 10:27:44,10.840660,10000788_54733468003
4,10001527,90885934252,5,5E ICU EUH,5E ICU EUH,2012-09-27 21:45:17,2012-09-28 15:00:27,0.718866,10001527_90885934252
...,...,...,...,...,...,...,...,...,...
189220,99995283,41747642827,189221,41 CCU ECLH,41 CCU ECLH,2015-05-17 07:53:44,2015-05-18 15:39:21,1.323345,99995283_41747642827
189221,99995283,76374197374,189222,41 CCU ECLH,41 CCU ECLH,2018-04-08 20:56:03,2018-04-09 17:58:46,0.876887,99995283_76374197374
189222,99995283,98208879646,189223,PACU II ECLH,21 ICU ECLH,2010-12-28 06:16:21,2010-12-29 12:13:20,1.247905,99995283_98208879646
189223,99997196,59639511443,189224,2SW ICU SJH,2SW ICU SJH,2017-09-23 12:38:48,2017-09-24 15:21:54,1.113264,99997196_59639511443
189224,99997229,71249926344,189225,3G CCU EUH,3G CCU EUH,2021-03-20 01:33:40,2021-03-22 21:10:46,2.817430,99997229_71249926344

In [32]:
df_icustays=df_icustays.drop(["subject_id", "hadm_id"], axis=1)
df_icustays

,stay_id,first_careunit,last_careunit,intime,outtime,los,subject_id_hadm_id
0,1,5E ICU EUH,5E ICU EUH,2015-05-12 18:29:30,2015-05-13 16:51:55,0.932234,10000683_29770490036
1,2,5E ICU EUH,5E ICU EUH,2015-05-13 17:16:17,2015-05-13 22:14:51,0.207338,10000683_29770490036
2,3,5E ICU EUH,5E ICU EUH,2015-09-08 12:10:12,2015-09-09 14:28:37,1.096123,10000683_87659254514
3,4,2SW ICU SJH,2SW ICU SJH,2017-02-01 14:17:11,2017-02-12 10:27:44,10.840660,10000788_54733468003
4,5,5E ICU EUH,5E ICU EUH,2012-09-27 21:45:17,2012-09-28 15:00:27,0.718866,10001527_90885934252
...,...,...,...,...,...,...,...
189220,189221,41 CCU ECLH,41 CCU ECLH,2015-05-17 07:53:44,2015-05-18 15:39:21,1.323345,99995283_41747642827
189221,189222,41 CCU ECLH,41 CCU ECLH,2018-04-08 20:56:03,2018-04-09 17:58:46,0.876887,99995283_76374197374
189222,189223,PACU II ECLH,21 ICU ECLH,2010-12-28 06:16:21,2010-12-29 12:13:20,1.247905,99995283_98208879646
189223,189224,2SW ICU SJH,2SW ICU SJH,2017-09-23 12:38:48,2017-09-24 15:21:54,1.113264,99997196_59639511443
189224,189225,3G CCU EUH,3G CCU EUH,2021-03-20 01:33:40,2021-03-22 21:10:46,2.817430,99997229_71249926344

In [34]:
df_icustays=df_icustays.drop(["stay_id"],axis=1)
df_icustays

,first_careunit,last_careunit,intime,outtime,los,subject_id_hadm_id
0,5E ICU EUH,5E ICU EUH,2015-05-12 18:29:30,2015-05-13 16:51:55,0.932234,10000683_29770490036
1,5E ICU EUH,5E ICU EUH,2015-05-13 17:16:17,2015-05-13 22:14:51,0.207338,10000683_29770490036
2,5E ICU EUH,5E ICU EUH,2015-09-08 12:10:12,2015-09-09 14:28:37,1.096123,10000683_87659254514
3,2SW ICU SJH,2SW ICU SJH,2017-02-01 14:17:11,2017-02-12 10:27:44,10.840660,10000788_54733468003
4,5E ICU EUH,5E ICU EUH,2012-09-27 21:45:17,2012-09-28 15:00:27,0.718866,10001527_90885934252
...,...,...,...,...,...,...
189220,41 CCU ECLH,41 CCU ECLH,2015-05-17 07:53:44,2015-05-18 15:39:21,1.323345,99995283_41747642827
189221,41 CCU ECLH,41 CCU ECLH,2018-04-08 20:56:03,2018-04-09 17:58:46,0.876887,99995283_76374197374
189222,PACU II ECLH,21 ICU ECLH,2010-12-28 06:16:21,2010-12-29 12:13:20,1.247905,99995283_98208879646
189223,2SW ICU SJH,2SW ICU SJH,2017-09-23 12:38:48,2017-09-24 15:21:54,1.113264,99997196_59639511443
189224,3G CCU EUH,3G CCU EUH,2021-03-20 01:33:40,2021-03-22 21:10:46,2.817430,99997229_71249926344

In [36]:
merged_icustays_microbiologyevents = pd.merge(df_icustays, df, on='subject_id_hadm_id', how='inner')
merged_icustays_microbiologyevents

,first_careunit,last_careunit,intime,outtime,los,subject_id_hadm_id,micro_specimen_id,chartdate,charttime,spec_type_desc,storetime,test_name,org_name,ab_itemid,ab_name,interpretation
0,2G ICU EUH,2G ICU EUH,2014-01-03 21:41:41,2014-01-06 23:00:00,3.054387,10008476_59065693895,21462800041537,2014-01-05,2014-01-05 11:20:00,Bronchial Washing,2014-01-07 11:04:54,RESPIRATORY CULTURE,Escherichia coli,309628,Tobramycin $,Susceptible
1,2G ICU EUH,2G ICU EUH,2014-01-03 21:41:41,2014-01-06 23:00:00,3.054387,10008476_59065693895,21462800041537,2014-01-05,2014-01-05 11:20:00,Bronchial Washing,2014-01-07 11:04:54,RESPIRATORY CULTURE,Escherichia coli,309642,Piperacillin,Resistant
2,2G ICU EUH,2G ICU EUH,2014-01-03 21:41:41,2014-01-06 23:00:00,3.054387,10008476_59065693895,21462800041537,2014-01-05,2014-01-05 11:20:00,Bronchial Washing,2014-01-07 11:04:54,RESPIRATORY CULTURE,Escherichia coli,309699,Aztreonam $$$$,Susceptible
3,2G ICU EUH,2G ICU EUH,2014-01-03 21:41:41,2014-01-06 23:00:00,3.054387,10008476_59065693895,21462800041537,2014-01-05,2014-01-05 11:20:00,Bronchial Washing,2014-01-07 11:04:54,RESPIRATORY CULTURE,Escherichia coli,309703,Ampicillin $,Resistant
4,2G ICU EUH,2G ICU EUH,2014-01-03 21:41:41,2014-01-06 23:00:00,3.054387,10008476_59065693895,21462800041537,2014-01-05,2014-01-05 11:20:00,Bronchial Washing,2014-01-07 11:04:54,RESPIRATORY CULTURE,Escherichia coli,664888,Levofloxacin $,Susceptible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186216,2E ICU SJH,2E ICU SJH,2018-10-02 18:52:51,2018-10-10 19:46:31,8.037269,99992121_65661024783,94457455067709,2018-10-02,2018-10-02 12:30:00,Incision,2018-10-06 07:53:51,WOUND/ABSCESS AER+ANA CULTURE,Escherichia coli,309693,Cefazolin $,Susceptible
1186217,2E ICU SJH,2E ICU SJH,2018-10-02 18:52:51,2018-10-10 19:46:31,8.037269,99992121_65661024783,94457455067709,2018-10-02,2018-10-02 12:30:00,Incision,2018-10-06 07:53:51,WOUND/ABSCESS AER+ANA CULTURE,Escherichia coli,309680,Ceftazidime $$,Susceptible
1186218,2E ICU SJH,2E ICU SJH,2018-10-02 18:52:51,2018-10-10 19:46:31,8.037269,99992121_65661024783,94457455067709,2018-10-02,2018-10-02 12:30:00,Incision,2018-10-06 07:53:51,WOUND/ABSCESS AER+ANA CULTURE,Escherichia coli,309641,Piperacillin/Tazobactam $$,Susceptible
1186219,2E ICU SJH,2E ICU SJH,2018-10-02 18:52:51,2018-10-10 19:46:31,8.037269,99992121_65661024783,94457455067709,2018-10-02,2018-10-02 12:30:00,Incision,2018-10-06 07:53:51,WOUND/ABSCESS AER+ANA CULTURE,Escherichia coli,664888,Levofloxacin $,Susceptible
1186220,2E ICU SJH,2E ICU SJH,2018-10-02 18:52:51,2018-10-10 19:46:31,8.037269,99992121_65661024783,94457455067709,2018-10-02,2018-10-02 12:30:00,Incision,2018-10-06 07:53:51,WOUND/ABSCESS AER+ANA CULTURE,Escherichia coli,309625,Amikacin $,Susceptible

In [37]:
merged_icustays_microbiologyevents.to_csv("merged_icustays_microbiologyevents.csv")