In [6]:
import pandas as pd

In [7]:
df_items = pd.read_parquet('../../ICU/tables/d_items.parquet')

In [8]:
df_lab_items = pd.read_parquet('../../ICU/tables/d_labitems.parquet')

In [9]:
df_labevents = pd.read_parquet('../../ICU/tables/labevents.parquet')

In [10]:
top_10 = df_labevents['itemid'].value_counts().head(10).index.tolist()

In [11]:
df_labevents = df_labevents[df_labevents['itemid'].isin(top_10)]

In [12]:
df_labevents = df_labevents.drop_duplicates(subset=['subject_id', 'hadm_id', 'itemid'])

In [14]:
df_labevents['subject_hadm_id'] = df_labevents['subject_id'].astype(str) + '_' + df_labevents['hadm_id'].astype(str)

In [15]:
df_labevents = df_labevents.pivot_table(
    index=['subject_id', 'hadm_id', 'subject_hadm_id'], 
    columns='itemid', 
    values='value', 
    aggfunc='first'
)

In [18]:
df_labevents = df_labevents.dropna()
df_labevents = df_labevents.drop_duplicates()

In [19]:
df_labevents

itemid                                      1512214 1512995 1513222  \
subject_id hadm_id     subject_hadm_id
10000100   58594204243 10000100_58594204243    15.0    3.61     608
10000214   57400481521 10000214_57400481521     7.5    4.39     244
10000364   68104421981 10000364_68104421981     7.2    4.69     250
10000422   36827033173 10000422_36827033173     4.7    5.49     149
10000562   28431526374 10000562_28431526374    10.2    5.16     326
...                                             ...     ...     ...
99999856   39743800534 99999856_39743800534     8.7    4.78     165
99999959   2127561032  99999959_2127561032     11.7    4.87     295
           6470596727  99999959_6470596727     10.9    4.92     255
99999991   77661750610 99999991_77661750610    5.69    3.50     261
99999997   48836056566 99999997_48836056566     8.0    4.41     217

itemid                                              1513394 1513468 1513471  \
subject_id hadm_id     subject_hadm_id
10000100   58594204243 10000100_58594204243            10.5    93.1    31.8
10000214   57400481521 10000214_57400481521            11.9    87.0    32.2
10000364   68104421981 10000364_68104421981            11.5    85.9    31.5
10000422   36827033173 10000422_36827033173  Not Applicable    63.2    26.5
10000562   28431526374 10000562_28431526374            10.1    79.5    33.2
...                                                     ...     ...     ...
99999856   39743800534 99999856_39743800534             9.8    81.8    31.7
99999959   2127561032  99999959_2127561032             10.3    83.0    33.9
           6470596727  99999959_6470596727              9.9    79.5    35.3
99999991   77661750610 99999991_77661750610             9.8   101.4    31.5
99999997   48836056566 99999997_48836056566             9.1    95.5    33.7

itemid                                      1513472 1513817 1513889 1513981
subject_id hadm_id     subject_hadm_id
10000100   58594204243 10000100_58594204243    29.6    10.7    33.6     130
10000214   57400481521 10000214_57400481521    28.0    12.3    38.2     119
10000364   68104421981 10000364_68104421981    27.1    12.7    40.3     169
10000422   36827033173 10000422_36827033173    16.8     9.2    34.7      85
10000562   28431526374 10000562_28431526374    26.4    13.6    41.0     294
...                                             ...     ...     ...     ...
99999856   39743800534 99999856_39743800534    25.9    12.4    39.1     113
99999959   2127561032  99999959_2127561032     28.1    13.7    40.4     114
           6470596727  99999959_6470596727     28.0    13.8    39.1      86
99999991   77661750610 99999991_77661750610    32.0    11.2    35.5     100
99999997   48836056566 99999997_48836056566    32.2    14.2    42.1      91

[1638264 rows x 10 columns]